version: '3.8'

services:
  backend:
    image: openjdk:17
    container_name: votingapi-backend
    working_dir: /app
    volumes:
      - ./target:/app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=

  db:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 

volumes:
  postgres-data:
